title: ShadowThreeD's Blog
author: ShadowThreeD
email: ShadowThreeD@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ShadowThreeD's ponsonal Blog for record my colorful life.

# social links
twitter_username: ShadowThreeD
github_username:  ShadowThreeD

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
